### ISSUE TITLE
Add minimap flare like in CHC

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/overthrow2#129]
Should have a wrapper around the minimap to show its Overthrow 2.0, its cooler. 
![image](https://user-images.githubusercontent.com/16277198/104908753-02865500-59db-11eb-8443-5eaa59f63db3.png)

**Comment by TheProma** [comment]
not a designer but mb this will work for now..
![image](https://user-images.githubusercontent.com/26060995/105703979-1a9c2e00-5f1f-11eb-8b12-f9cf0515aefa.png)

**Comment by natoshi** [comment]
How is this?
![image](https://user-images.githubusercontent.com/3074666/106028541-c175fb00-60d4-11eb-8604-c8e02bc919b4.png)


Less flashy versions:
![image](https://user-images.githubusercontent.com/3074666/106028680-e9655e80-60d4-11eb-9d4b-f813088168ed.png)

Could also code it so that it becomes more flashy as the game progresses.

**Comment by darklordabc** [comment]
Added
